Feature/telas usuario perfil
Nocs-lab/inbcm-admin-frontend pull request #11
Opened 2024-07-14 18:41 UTC by thfields

2024-07-15 13:07 UTC, Everbero approved these changes

2024-07-15 13:40 UTC, Everbero requested changes
Os arquivos não comentados apresentam problemas similares. Falta de feeback visual em caso de erros, a lógica de declaração de constante antes da utilização.

Além disso há inconsistências na formatação e indentação do código, recomendo aplicar o prettier e lint antes do envio.

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/[id]/index.tsx
> +  const navigate = useNavigate()
Você está utilizando useNavigate fora do escopo do componente useMutation. Isso pode ser corrigido movendo a declaração de navigate para cima.

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/[id]/index.tsx
> +  const navigate = useNavigate()
A variável navigate é usada antes de ser definida. Ela deve ser definida antes do useMutation.

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/[id]/index.tsx
> +  const [{ data: profile }, { data: permissions }] = useSuspenseQueries(
useSuspenseQueries não deveria ser utilizado em conjunto de um componente com suspense?

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/[id]/index.tsx
> +  const onSubmit = async ({ name, description, permissions }: FormData) => {
mutate não é assíncrona

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/[id]/index.tsx
> +    throw new Error('perfil nao encontrado');
throw não irá quebrar a aplicação?

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/[id]/index.tsx
> +    throw new Error('perfil nao encontrado');
quero dizer, não é necessário informar o erro para o usuário na interface?

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/createProfile.tsx
> +  const navigate = useNavigate()
mesmo problema

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/index.tsx
> +  return response.json();
Não há tratamento de erro para response.json(), que pode falhar se a resposta não for um JSON válido.

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/index.tsx
> +  const handleDeleteProfile = async () => {
A função de deletar perfil não desativa o botão ou exibe um estado de carregamento, o que pode permitir múltiplos cliques e deletar perfis incorretamente.

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/index.tsx
> +          <input type="text" placeholder="Pesquisar Perfis" className="input mr-2" />
o campo de pessquisa não tem um método associado

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/index.tsx
> +                    (permission) => permission.name).join(', ')}</td>
profile.permissionss assume que cada permission tem um campo name, mas o tipo Profile define permissions como string[]. Isso pode causar erros de execução se permissions não contiver objetos.

2024-07-15 13:40 UTC, Everbero commented on src/pages/profiles/modalDeleteProfile.tsx
> +        <button className="btn btn-red mr-2" onClick={handleDelete}>Excluir</button>
Desabilite o botão de exclusão durante a operação

2024-07-15 18:23 UTC, vadolasi commented on src/pages/profiles/[id]/index.tsx
> +  const [{ data: profile }, { data: permissions }] = useSuspenseQueries(
O componente de Suspense está declarado em um elemento pai.

2024-07-15 20:39 UTC, thfields commented
commit com as alterações: 79a2c4017a8bd02666e4f1700c1c57fb23329999

2024-07-16 20:07 UTC, Everbero requested changes
Este tratamento de erro está redundante, 2 try catch são executados para a mesma resposta.

2024-07-23 19:40 UTC, closed without merging