Feature/gerenciamento usuario profile
Nocs-lab/inbcm-admin-frontend pull request #6
Opened 2024-07-02 22:10 UTC by thfields

2024-07-03 13:00 UTC, Everbero requested changes
Além dos comentários adicionados nos locais onde foi usado font-awesome não é possível utilizar o componente FontAwesomeIcon?

2024-07-03 13:00 UTC, Everbero commented on src/pages/profiles/[id]/index.tsx
Os dados do perfil e das permissões estão sendo buscados duas vezes - uma vez dentro do useQuery e outra dentro do useEffect.

Após a submissão do formulário, o refetch é chamado, mas como você navega para outra página imediatamente após, isso é desnecessário.

O  useEffect que busca os dados iniciais tem uma dependência de id, mas isso é redundante, pois o useQuery já está fazendo isso.

Falta de tratamento de erro em fetchProfileById e fetchPermissions: Os erros são lançados mas não tratados apropriadamente.

O estado permissions poderia utilizar o tipo Permission[] explicitamente.

A mesma verificação de carregamento e erro ocorre duas vezes, uma no useQuery e outra no useEffect.

2024-07-03 13:00 UTC, Everbero commented on src/pages/profiles/index.tsx
Os ícones NotePencil, TrashSimple, e UserPlus foram importados do @phosphor-icons/react, mas não foram utilizados. Em vez disso, ícones Font Awesome foram usados.

Adicionar descrições ou labels acessíveis para os botões que contêm apenas ícones.

Adicionar um indicador de carregamento durante a busca.

Definir tipos de dados para as respostas da API.

2024-07-03 13:00 UTC, Everbero commented on src/pages/profiles/createProfile.tsx
Adicione tipos explícitos para respostas da API.

Adicionar feedback visual para o usuário, monstrando estados de carregamento ou erros.

Verificar e remover estados não necessários.

2024-07-03 13:00 UTC, Everbero commented on src/pages/usuarios/createUser.tsx
> +        // Tratar erro aqui, se necessário
bad prompt

2024-07-03 13:00 UTC, Everbero commented on src/pages/usuarios/createUser.tsx
> +      // Tratar erro aqui, se necessário
bad prompt

2024-07-03 13:00 UTC, Everbero commented on src/pages/usuarios/[id]/index.tsx
O useQuery já está buscando os dados do usuário, mas o useEffect também está fazendo a mesma coisa.

No useEffect, a atualização do estado de editedUser ocorre imediatamente após a busca dos dados, o que pode causar uma condição de corrida (race condition). A mesma questão se aplica à busca de perfis.

Se a chamada para buscar perfis falhar, o editedUser ainda pode ser atualizado. Idealmente, a atualização de editedUser deve ocorrer apenas após ambos, os dados do usuário e os perfis, serem carregados com sucesso.

O useEffect depende apenas de id. No entanto, ele deve ser dividido em dois useEffects, um para buscar o usuário e outro para buscar os perfis.

Embora erros sejam registrados no console, não há feedback ao usuário caso ocorra um erro ao buscar dados.

2024-07-03 13:00 UTC, Everbero commented on src/pages/usuarios/createUser.tsx
Mostrar feedback ao usuário enquanto os perfis são carregados ou se ocorrer um erro.

2024-07-03 15:51 UTC, thfields commented
por enquanto não está sendo usado o componente do FontAwesomeIcon, e sim apenas o html. tentei fazer as outras correções no commit também. 

76f1d5fbfeb9283a177ba7f8a8ce8bfbf9ad0e87

2024-07-11 15:57 UTC, Everbero approved these changes

2024-07-11 15:58 UTC, Everbero commented
@thfields você está introduzindo conflitos no pnpm-lock.yaml por favor faz um novo commit com as libs sincronizadas.

2024-07-11 23:59 UTC, thfields commented
ainda não terminei, falta inserir o novo componente de multi-select.

2024-07-12 16:35 UTC, closed without merging

2024-07-12 16:35 UTC, Everbero commented
Então vou fechar o PR e você envia completo.